### ISSUE TITLE
Error upon running bot

### ISSUE THREAD

**Issue by avocardow** [AaronCQL/bluna-bot#2]
Hey, just getting an error when running the bot. Not sure if it's an issue, if it's me, or if it's Terra itself.
Thought I'd copy the error text here. Hopefully it's helpful, or you can tell me what I'm doing wrong 🤣 
Thank you for all your help.

```
Error: getaddrinfo ENOTFOUND lcd.terra.dev
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'lcd.terra.dev',
  config: {
    url: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store',
    method: 'get',
    headers: { Accept: 'application/json', 'User-Agent': 'axios/0.21.1' },
    params: {
      query_msg: '{"balance":{"address":"terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8"}}'
    },
    baseURL: 'https://lcd.terra.dev',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'lcd.terra.dev',
      port: null,
      nativeProtocols: [Object],
      pathname: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store',
      search: '?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: lcd.terra.dev\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lcd.terra.dev',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://lcd.terra.dev/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

Unknown error encountered! Stopping program...
```

**Comment by AaronCQL** [comment]
Hmm, this seems to be an issue with your network or DNS resolver? It's trying to query your wallet balance using your address, but seems like it's not resolving the terra API endpoint correctly. Try visiting https://lcd.terra.dev/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp on your browser. If you can see some non-error response, then this program shouldn't be throwing this error either.

**Comment by avocardow** [comment]
Unfortunately I get nothing. "This site can’t be reached"
Should I be seeing a webpage here?
![image](https://user-images.githubusercontent.com/17078357/125639732-1687fee2-a515-473b-83d4-77fa9b5ec11b.png)

**Comment by AaronCQL** [comment]
You should see something similar to this:

![image](https://user-images.githubusercontent.com/28671644/125640183-17d46897-cb22-44f0-9e81-6f550385d2cc.png)

But you getting an error on your browser confirms my suspicion: your DNS resolver is unable to resolve the terra API endpoint 🤣. Not sure what changed between your previous use, but you may want to google the `DNS_PROBE_FINISHED_NXDOMAIN` error shown on your browser to find out if you can fix the DNS resolver on your side.

**Comment by avocardow** [comment]
Thank you. I changed my dns and I am able to see that webpage.
![image](https://user-images.githubusercontent.com/17078357/125643356-a59df05f-b651-4b66-a711-79bd228f5423.png)

However on trying to run the bot I get this...

```
Error: getaddrinfo ENOTFOUND lcd.terra.dev
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'lcd.terra.dev',
  config: {
    url: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store',
    method: 'get',
    headers: { Accept: 'application/json', 'User-Agent': 'axios/0.21.1' },
    params: {
      query_msg: '{"balance":{"address":"terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8"}}'
    },
    baseURL: 'https://lcd.terra.dev',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'lcd.terra.dev',
      port: null,
      nativeProtocols: [Object],
      pathname: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store',
      search: '?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: lcd.terra.dev\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lcd.terra.dev',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://lcd.terra.dev/wasm/contracts/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp/store?query_msg=%7B%22balance%22:%7B%22address%22:%22terra1m43rpw28grr3530j4rl99g0t7cmgqzh7rah9g8%22%7D%7D',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

Unknown error encountered! Stopping program...
```

Which is exactly the same problem 😞 
Sorry about this 😅

**Comment by avocardow** [comment]
The reason I thought it may be Terra and not me (besides wanting to not be the one who broke something), is cause I also can't view my wallet on any device at the moment. Just getting this message:
![image](https://user-images.githubusercontent.com/17078357/125646858-d3b1adcc-ddc2-435a-974b-d37b73fefc82.png)

**Comment by AaronCQL** [comment]
The terra wallet is hitting the exact same API that this bot uses - makes sense for both of them to not work simultaneously. Not sure what you did to fix your DNS, but make sure it applies to the terminal you are running this bot on, and where you are viewing your wallet from. Best to check with the terra team directly if this issue persists.

**Comment by avocardow** [comment]
Didn't change anything, just left it until morning. Woke up and can't connect to my wallet, but the bot runs so I don't care 🤣
Thank you
